### ISSUE TITLE
dans lancienne correc, il est dit quon peut utiliser la meme texture pour deux murs, toi tu as bloque cela, on le debloque ou ya une raison ?

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_cub3d#11]
Error
Same textures detected

**Comment by melobern** [comment]
Sujet :
`Vous devez afficher des textures différentes (vous avez le choix) selon si les murs sont face nord, sud, est, ouest`

Si les correcteurs l'interprètent différemment, ça n'aurait aucun sens de mettre zéro pour un check quand le sujet demande des textures différentes et pas "vous devez pouvoir afficher les textures assignées à chaque mur" ce qui enlèverait la consigne que ça doit être différent.
