### ISSUE TITLE
map qui saffiche alors quil y a des 0 et pas des 1 sur le côté 

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_cub3d#12]
ici jai mis des 0 tout en bas a gauche et sur le côté gauche, la map ne devrait pas safficher : 

sujet : 
 The map must be closed/surrounded by walls, if not the program must return
an error.

 main {2} U:4  ~/cub3d                                    22:01:04  fanny 
❯ ./cub3D /home/fanny/cub3d/grande_map.cub
TMP_MAP
NO /home/fanny/cub3d/textures/test/north.xpm
SO /home/fanny/cub3d/textures/test/south.xpm
WE /home/fanny/cub3d/textures/test/west.xpm
EA /home/fanny/cub3d/textures/test/east.xpm

C 125, 230, 4
F 124, 23, 14

11111111111111111111111111111111111111111111
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000010000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
00000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
10000000000000000000000000000000000000000001
100000000000000000000S0000000000000000000001
10001111111111111111111111111111111111111111
1001
1001
0111

**Comment by melobern** [comment]
Normal je n'ai pas encore codé les fonctions qui permettront de vérifier ça. Donc pas de magie :D Je le fais demain.

**Comment by melobern** [comment]
Alors j'ai plutôt le problème inverse maintenant : des maps considérées invalides, comme montré dans #13 . Tous les tests sur les maps non closes donnant bien l'erreur "Map not close" Je ferme cette issue.
