### ISSUE TITLE
Maps considérées incorrectes par erreur 

### ISSUE THREAD

**Issue by melobern** [faboussard/42_cub3d#13]
Ces maps ne devraient pas être considérées invalides, mais le sont, et ce avant même que l'on passe dans la fonction de vérification de la map ouverte/fermée.

- ./cub3D/maps/good/test_map_hole.cub
> Error
> Invalid map
> 

- ./cub3D/maps/good/test_whitespace.cub
> Error
> Invalid map

**Comment by faboussard** [comment]
✗ ./cub3D  map_correcte/grande_map4.cub
Error
: Map isn't closed

celle la aussi ?

**Comment by melobern** [comment]
> ✗ ./cub3D  map_correcte/grande_map4.cub
> Error
> : Map isn't closed
> 
> celle la aussi ? 

Celle-là est sujette à interprétation. On peut décider que des 0 en dehors de la carte font que la map est invalide tout court, ou décider de partir du joueur.

Si j'arrive à partir du joueur sans que ça impacte trop les performances (et que ça fonctionne correctement, ce qui n'a pas été le cas sur mes essais du week-end ^^) je le ferai.

Mais sinon, je partirai du principe qu'un 0 en dehors de la map est invalide par défaut.

**Comment by melobern** [comment]
J'ai pu faire la fonction récursive pour verifier à partir de la position du joueur. Par contre elle ne fonctionne pas si on enlève le verrou des maps de plus de 50 000 caractères. Donc si on peut bien le garder, c'est mieux^^
