### ISSUE TITLE
erreur suppressed valgrind -s :  used_suppression: 1 X on SUSE11 writev uninit padding /usr/libexec/valgrind/default.supp:377

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_cub3d#9]
Loading texture 0 from path: /home/faboussa/cub3d/9186397_20240110082936587_1_LARGE.jpg
Error loading texture's picture: Resource temporarily unavailable
==222131== 
==222131== HEAP SUMMARY:
==222131==     in use at exit: 0 bytes in 0 blocks
==222131==   total heap usage: 878 allocs, 878 frees, 2,641,555 bytes allocated
==222131== 
==222131== All heap blocks were freed -- no leaks are possible
==222131== 
==222131== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)
--222131-- 
--222131-- used_suppression:      1 X on SUSE11 writev uninit padding /usr/libexec/valgrind/default.supp:377
==222131== 
==222131== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)

**Comment by melobern** [comment]
Si elle est suppressed, normalement on n'a pas à s'en occuper. On peut chercher quelle erreur est suppressed en regardant la ligne 377 de `/usr/libexec/valgrind/default.supp` :

``` cpp
{
   X on SUSE11 writev uninit padding
   Memcheck:Param
   writev(vector[...])
   fun:writev
   obj:/usr/lib*/libxcb.so*
   obj:/usr/lib*/libxcb.so*
}
```

J'ai demandé au Chat Mistral de m'expliquer en quoi consistait cette erreur : 

> Il semble que vous ayez fourni un extrait d'un rapport généré par l'outil de débogage mémoire Memcheck de Valgrind. L'erreur mentionnée dans cet extrait est liée à l'utilisation de la fonction writev() dans la bibliothèque libxcb.so sur un système SUSE11.
> 
> L'erreur spécifique est "uninit padding", ce qui signifie que la fonction writev() utilise des données non initialisées dans le tampon de remplissage. Cela peut entraîner des comportements imprévisibles et des erreurs de segmentation.
> 
> Pour corriger cette erreur, vous devez vous assurer que toutes les données utilisées par writev() sont correctement initialisées avant d'être passées à la fonction. Vous pouvez utiliser des fonctions telles que memset() pour initialiser les tampons de données avant de les utiliser.
> 
> Si vous n'êtes pas le développeur de la bibliothèque libxcb.so, vous devriez signaler cette erreur aux développeurs responsables de cette bibliothèque. Ils devraient être en mesure de fournir un correctif pour cette erreur dans une future version de la bibliothèque.

Concrètement, ce n'est pas nous qui utilisons `writev` et l'erreur est suppressed.

En revanche, concernant le fait de bloquer la texture si elle n'est pas xpm, c'est effectivement ce que je compte faire.
